### ISSUE TITLE
Cannot GET /api/pool/on

### ISSUE THREAD

**Issue by ivanvach** [mikemucc/screenlogic-api#18]
I'm getting this response

Cannot GET /api/pool/on

when trying

<ip address:port>/api/pool/on

at the same time

<ip address:port>/api/all 

does work, which means that the IP address and port are correct and the app is running.

**Comment by mikemucc** [comment]
That is because` /api/pool/on` is not a valid route for a GET request.

According to [the readme](https://github.com/mikemucc/screenlogic-api#put-methods), `/api/pool/on` is only valid as a PUT request.
