### ISSUE TITLE
Can't start the pool by PUT command

### ISSUE THREAD

**Issue by ivanvach** [mikemucc/screenlogic-api#19]
Trying this using "Postman" software for Windows 10

HTTP PUT

192.168.1.149:3000/api/pool/on

Payload: none

Getting the response below. Also tried putting payload=1 and also 192.168.1.149:3000/api/pool without the suffix on and put "on" as payload. Every time same response

<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<title>Error</title>
</head>

<body>
	<pre>Cannot POST /api/pool/on</pre>
</body>

</html>

**Comment by mikemucc** [comment]
It looks like you're doing a POST not a PUT from the last line of the output you pasted above.

``` 
$ curl -X PUT localhost:3000/api/pool/off
{
  "body": "pool",
  "action": "off",
  "sent": true
}
```

**Comment by ivanvach** [comment]
Oooops my bad. It works with put
